[book]
authors = ["Andy Frank Schoknecht"]
language = "en"
multilingual = false
src = "src"
title = "The C Programming Language, a 50 years old foundation"
create-missing = false

[output.html]
git-repository-url = "https://github.com/SchokiCoder/c_50_years_old_foundation"

[output.html.print]
enable = true
