build:
	cd "1_main" && make
	cd ".."
	
	cd "2_types-and-variables" && make
	cd ".."
	
	cd "3_functions" && make
	cd ".."
	
	cd "4_operators101" && make
	cd ".."
	
	cd "5_conditions" && make
	cd ".."
	
	cd "6_loops" && make
	cd ".."
	
	cd "7_simple-text" && make
	cd ".."
	
	cd "8_arrays" && make
	cd ".."
	
	cd "9_comments" && make
	cd ".."
	
	cd "10_formatting" && make
	cd ".."
	
	#cd "11_include" && make
	#cd ".."
	
	#cd "12_buid-routines" && make
	#cd ".."
	
	cd "13_namespaces" && make
	cd ".."
	
	cd "14_pointers" && make
	cd ".."
	
	cd "15_structures" && make
	cd ".."
	
	cd "16_enumerators" && make
	cd ".."
	
	cd "17_casting" && make
	cd ".."
	
	cd "18_debugging" && make
	cd ".."
	
	cd "19_professionals-have-standards" && make
	cd ".."
	
	cd "20_roads-to-rome" && make
	cd ".."
	
	cd "21_optional-end-topics" && make
	cd ".."
