all: 36_faulty-code 37_correct-code

36_faulty-code:
	cc "$@.c" "faulty_string.c" "string_utils.c" -o "../binaries/$@" -g -Wall -Wextra

37_correct-code:
	cc "$@.c" "correct_string.c" "string_utils.c" -o "../binaries/$@" -g -Wall -Wextra