all: if else else-if no-brackets switch boolean logical

if:
	cc "$@.c" -o "$@" -g -Wall -Wextra

else:
	cc "$@.c" -o "$@" -g -Wall -Wextra

else-if:
	cc "$@.c" -o "$@" -g -Wall -Wextra

no-brackets:
	cc "$@.c" -o "$@" -g -Wall -Wextra

switch:
	cc "$@.c" -o "$@" -g -Wall -Wextra

boolean:
	cc "$@.c" -o "$@" -g -Wall -Wextra

logical:
	cc "$@.c" -o "$@" -g -Wall -Wextra
