all: 7_if 8_else 9_else-if 10_no-brackets 11_switch 12_boolean 13_logical

7_if:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra

8_else:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra

9_else-if:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra

10_no-brackets:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra

11_switch:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra

12_boolean:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra

13_logical:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra
