all: 14_while 15_do-while 16_for 17_loop-control

14_while:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra

15_do-while:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra
	
16_for:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra

17_loop-control:
	cc "$@.c" -o "../binaries/$@" -g -Wall -Wextra
