all: while do-while for loop-control

while:
	cc "$@.c" -o "$@" -g -Wall -Wextra

do-while:
	cc "$@.c" -o "$@" -g -Wall -Wextra
	
for:
	cc "$@.c" -o "$@" -g -Wall -Wextra

loop-control:
	cc "$@.c" -o "$@" -g -Wall -Wextra
